version: '3'

services:
  vite_docker:
    build:
      context: ./landing_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./landing_frontend:/app:delegated
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: yarn start
  web:
    build:
      context: ./landing_backend
    volumes:
      - ./landing_backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: yourdbuser
      POSTGRES_PASSWORD: yourdbpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
